### ISSUE TITLE
mysql的bit类型字段生成模型有问题

### ISSUE THREAD

**Issue by shangcloud** [boiawang/sequelize-db-export-import#6]
mysql的bit类型字段生成模型type为空，如sex是bit，生成后就空了
sex: {
            type: ,
}

**Comment by boiawang** [comment]
bit的类型是什么  boolean吗？一般这样的我都用tinyint为1的

**Comment by shangcloud** [comment]
对，类似于boolean，只有2个值，求解决喵~~~~

**Comment by boiawang** [comment]
fix 0.1.8
