### ISSUE TITLE
database name(-d) is needed

### ISSUE THREAD

**Issue by Nowforpasserby** [boiawang/sequelize-db-export-import#7]
![image](https://user-images.githubusercontent.com/9143951/28709175-bddd9606-73b1-11e7-8006-a29dcdb3b902.png)

**Comment by shaunplumb** [comment]
This issue is now resolved if the database is in the config with the merge of my pull request

**Comment by shaunplumb** [comment]
@Nowforpasserby this issue is now resolved with the merge of my pull request.
